apiVersion: v1
kind: Service
metadata:
  name: nordlynx
  namespace: nordlynx
spec:
  selector:
    app: nordlynx
  ports:
    - name: qbittorrent
      port: 8088
      targetPort: 8088
    - name: torrent
      port: 6881
      targetPort: 6881
